-- MySQL Script generated by MySQL Workbench
-- Sat Feb 22 18:53:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Study` (
  `idStudy` INT NOT NULL,
  PRIMARY KEY (`idStudy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Experiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Experiment` (
  `idExperiment` INT NOT NULL,
  `Study_idStudy` INT NOT NULL,
  PRIMARY KEY (`idExperiment`),
  INDEX `fk_Experiment_Study1_idx` (`Study_idStudy` ASC) VISIBLE,
  CONSTRAINT `fk_Experiment_Study1`
    FOREIGN KEY (`Study_idStudy`)
    REFERENCES `mydb`.`Study` (`idStudy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Feature` (
  `idFeature` INT NOT NULL,
  `featureName` VARCHAR(45) NULL,
  PRIMARY KEY (`idFeature`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dataset` (
  `idDataset` INT NOT NULL,
  `targetFeature_idFeature` INT NOT NULL,
  `versionModel` FLOAT NULL,
  `nameModel` VARCHAR(45) NULL,
  PRIMARY KEY (`idDataset`),
  INDEX `fk_Data_Feature1_idx` (`targetFeature_idFeature` ASC) VISIBLE,
  CONSTRAINT `fk_Data_Feature1`
    FOREIGN KEY (`targetFeature_idFeature`)
    REFERENCES `mydb`.`Feature` (`idFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TaskType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TaskType` (
  `idTaskType` INT NOT NULL,
  `taskType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTaskType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `idTask` INT NOT NULL,
  `Data_idData` INT NOT NULL,
  `TaskType_idTaskType` INT NOT NULL,
  `startTrainTimestamp` TIMESTAMP(6) NULL,
  `endTrainTimestamp` TIMESTAMP(6) NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_Task_Data1_idx` (`Data_idData` ASC) VISIBLE,
  INDEX `fk_Task_TaskType1_idx` (`TaskType_idTaskType` ASC) VISIBLE,
  CONSTRAINT `fk_Task_Data1`
    FOREIGN KEY (`Data_idData`)
    REFERENCES `mydb`.`Dataset` (`idDataset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_TaskType1`
    FOREIGN KEY (`TaskType_idTaskType`)
    REFERENCES `mydb`.`TaskType` (`idTaskType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `idModel` INT NOT NULL,
  `scriptModel` TINYBLOB NULL,
  `versionModel` FLOAT NULL,
  `nameModel` VARCHAR(45) NULL,
  PRIMARY KEY (`idModel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Run`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Run` (
  `idRun` INT NOT NULL,
  `timestamp` TIMESTAMP(6) NULL,
  `Experiment_idExperiment` INT NOT NULL,
  `Task_idTask` INT NOT NULL,
  `Model_idModel` INT NOT NULL,
  PRIMARY KEY (`idRun`, `Model_idModel`),
  INDEX `fk_Run_Experiment_idx` (`Experiment_idExperiment` ASC) VISIBLE,
  INDEX `fk_Run_Task1_idx` (`Task_idTask` ASC) VISIBLE,
  INDEX `fk_Run_Flow1_idx` (`Model_idModel` ASC) VISIBLE,
  CONSTRAINT `fk_Run_Experiment`
    FOREIGN KEY (`Experiment_idExperiment`)
    REFERENCES `mydb`.`Experiment` (`idExperiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Run_Task1`
    FOREIGN KEY (`Task_idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Run_Flow1`
    FOREIGN KEY (`Model_idModel`)
    REFERENCES `mydb`.`Model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EvaluationProcedure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EvaluationProcedure` (
  `idEvaluationProcedure` INT NOT NULL,
  `scriptEvaluation` TINYBLOB NULL,
  PRIMARY KEY (`idEvaluationProcedure`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EvaluationSpecification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EvaluationSpecification` (
  `idEvaluationSpecification` INT NOT NULL,
  `EvaluationProcedure_idEvaluationProcedure` INT NOT NULL,
  `Task_idTask` INT NOT NULL,
  PRIMARY KEY (`idEvaluationSpecification`),
  INDEX `fk_EvaluationSpecification_EvaluationProcedure1_idx` (`EvaluationProcedure_idEvaluationProcedure` ASC) VISIBLE,
  INDEX `fk_EvaluationSpecification_Task1_idx` (`Task_idTask` ASC) VISIBLE,
  CONSTRAINT `fk_EvaluationSpecification_EvaluationProcedure1`
    FOREIGN KEY (`EvaluationProcedure_idEvaluationProcedure`)
    REFERENCES `mydb`.`EvaluationProcedure` (`idEvaluationProcedure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EvaluationSpecification_Task1`
    FOREIGN KEY (`Task_idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EvaluationMeasure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EvaluationMeasure` (
  `idEvaluationMeasure` INT NOT NULL,
  `measureValue` VARCHAR(45) NULL,
  `EvaluationSpecification_idEvaluationSpecification` INT NOT NULL,
  `Run_idRun` INT NOT NULL,
  `Run_Model_idModel` INT NOT NULL,
  PRIMARY KEY (`idEvaluationMeasure`),
  INDEX `fk_EvaluationMeasure_EvaluationSpecification1_idx` (`EvaluationSpecification_idEvaluationSpecification` ASC) VISIBLE,
  INDEX `fk_EvaluationMeasure_Run1_idx` (`Run_idRun` ASC, `Run_Model_idModel` ASC) VISIBLE,
  CONSTRAINT `fk_EvaluationMeasure_EvaluationSpecification1`
    FOREIGN KEY (`EvaluationSpecification_idEvaluationSpecification`)
    REFERENCES `mydb`.`EvaluationSpecification` (`idEvaluationSpecification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EvaluationMeasure_Run1`
    FOREIGN KEY (`Run_idRun` , `Run_Model_idModel`)
    REFERENCES `mydb`.`Run` (`idRun` , `Model_idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DatasetFeature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DatasetFeature` (
  `idDatasetFeature` INT NOT NULL,
  `Feature_idFeature` INT NOT NULL,
  `Dataset_idDataset` INT NOT NULL,
  PRIMARY KEY (`idDatasetFeature`),
  INDEX `fk_Dataset_Feature1_idx` (`Feature_idFeature` ASC) VISIBLE,
  INDEX `fk_Dataset_Data1_idx` (`Dataset_idDataset` ASC) VISIBLE,
  CONSTRAINT `fk_Dataset_Feature1`
    FOREIGN KEY (`Feature_idFeature`)
    REFERENCES `mydb`.`Feature` (`idFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dataset_Data1`
    FOREIGN KEY (`Dataset_idDataset`)
    REFERENCES `mydb`.`Dataset` (`idDataset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ModelParameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ModelParameter` (
  `idModelParameter` INT NOT NULL,
  `valueModelParameter` VARCHAR(45) NULL,
  `nameModelParameter` VARCHAR(45) NULL,
  `Run_idRun` INT NOT NULL,
  `Run_Model_idModel` INT NOT NULL,
  PRIMARY KEY (`idModelParameter`),
  INDEX `fk_ModelParameter_Run1_idx` (`Run_idRun` ASC, `Run_Model_idModel` ASC) VISIBLE,
  CONSTRAINT `fk_ModelParameter_Run1`
    FOREIGN KEY (`Run_idRun` , `Run_Model_idModel`)
    REFERENCES `mydb`.`Run` (`idRun` , `Model_idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
