-- MySQL Script generated by MySQL Workbench
-- Fri Apr 11 17:18:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Study` (
  `idStudy` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idStudy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Experiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Experiment` (
  `idExperiment` INT NOT NULL AUTO_INCREMENT,
  `idStudy` INT NOT NULL,
  PRIMARY KEY (`idExperiment`),
  INDEX `fk_Experiment_Study1_idx` (`idStudy` ASC) VISIBLE,
  CONSTRAINT `fk_Experiment_Study1`
    FOREIGN KEY (`idStudy`)
    REFERENCES `mydb`.`Study` (`idStudy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dataset` (
  `idDataset` INT NOT NULL AUTO_INCREMENT,
  `targetFeature` VARCHAR(45) NULL,
  `data` LONGBLOB NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idDataset`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TaskType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TaskType` (
  `idTaskType` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTaskType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `idDataset` INT NOT NULL,
  `idTaskType` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_Task_Data1_idx` (`idDataset` ASC) VISIBLE,
  INDEX `fk_Task_TaskType1_idx` (`idTaskType` ASC) VISIBLE,
  CONSTRAINT `fk_Task_Data1`
    FOREIGN KEY (`idDataset`)
    REFERENCES `mydb`.`Dataset` (`idDataset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_TaskType1`
    FOREIGN KEY (`idTaskType`)
    REFERENCES `mydb`.`TaskType` (`idTaskType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `idModel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `version` VARCHAR(45) NULL,
  `object` LONGBLOB NULL,
  PRIMARY KEY (`idModel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Run`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Run` (
  `idRun` INT NOT NULL AUTO_INCREMENT,
  `createdTimestamp` TIMESTAMP(6) NULL,
  `idExperiment` INT NULL,
  `idTask` INT NOT NULL,
  `idModel` INT NOT NULL,
  PRIMARY KEY (`idRun`, `idModel`),
  INDEX `fk_Run_Experiment_idx` (`idExperiment` ASC) VISIBLE,
  INDEX `fk_Run_Task1_idx` (`idTask` ASC) VISIBLE,
  INDEX `fk_Run_Flow1_idx` (`idModel` ASC) VISIBLE,
  CONSTRAINT `fk_Run_Experiment`
    FOREIGN KEY (`idExperiment`)
    REFERENCES `mydb`.`Experiment` (`idExperiment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Run_Task1`
    FOREIGN KEY (`idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Run_Flow1`
    FOREIGN KEY (`idModel`)
    REFERENCES `mydb`.`Model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EvaluationProcedure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EvaluationProcedure` (
  `idEvaluationProcedure` INT NOT NULL AUTO_INCREMENT,
  `object` TINYBLOB NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idEvaluationProcedure`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Measure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Measure` (
  `idMeasure` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `idRun` INT NOT NULL,
  `idEvaluationProcedure` INT NOT NULL,
  PRIMARY KEY (`idMeasure`, `idEvaluationProcedure`),
  INDEX `fk_EvaluationMeasure_Run1_idx` (`idRun` ASC) VISIBLE,
  INDEX `fk_Measure_EvaluationProcedure1_idx` (`idEvaluationProcedure` ASC) VISIBLE,
  CONSTRAINT `fk_EvaluationMeasure_Run1`
    FOREIGN KEY (`idRun`)
    REFERENCES `mydb`.`Run` (`idRun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Measure_EvaluationProcedure1`
    FOREIGN KEY (`idEvaluationProcedure`)
    REFERENCES `mydb`.`EvaluationProcedure` (`idEvaluationProcedure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ParameterType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ParameterType` (
  `idParameterType` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idParameterType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parameter` (
  `idParameter` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `idRun` INT NOT NULL,
  `idParameterType` INT NOT NULL,
  `valueType` VARCHAR(45) NULL,
  PRIMARY KEY (`idParameter`, `idParameterType`),
  INDEX `fk_ModelParameter_Run1_idx` (`idRun` ASC) VISIBLE,
  INDEX `fk_Parameter_ParameterType1_idx` (`idParameterType` ASC) VISIBLE,
  CONSTRAINT `fk_ModelParameter_Run1`
    FOREIGN KEY (`idRun`)
    REFERENCES `mydb`.`Run` (`idRun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parameter_ParameterType1`
    FOREIGN KEY (`idParameterType`)
    REFERENCES `mydb`.`ParameterType` (`idParameterType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`TaskType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`TaskType` (`idTaskType`, `type`) VALUES (1, 'Classification');
INSERT INTO `mydb`.`TaskType` (`idTaskType`, `type`) VALUES (2, 'Regression');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ParameterType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ParameterType` (`idParameterType`, `name`) VALUES (1, 'Model');
INSERT INTO `mydb`.`ParameterType` (`idParameterType`, `name`) VALUES (2, 'Task');

COMMIT;

