-- MySQL Script generated by MySQL Workbench
-- Mon May 26 16:40:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Dataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dataset` (
  `idDataset` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `startTimestamp` TIMESTAMP(6) NULL,
  `endTimestamp` TIMESTAMP(6) NULL,
  PRIMARY KEY (`idDataset`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TaskType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TaskType` (
  `idTaskType` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTaskType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `idDataset` INT NOT NULL,
  `idTaskType` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_Task_Data1_idx` (`idDataset` ASC) VISIBLE,
  INDEX `fk_Task_TaskType1_idx` (`idTaskType` ASC) VISIBLE,
  CONSTRAINT `fk_Task_Data1`
    FOREIGN KEY (`idDataset`)
    REFERENCES `mydb`.`Dataset` (`idDataset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_TaskType1`
    FOREIGN KEY (`idTaskType`)
    REFERENCES `mydb`.`TaskType` (`idTaskType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Model` (
  `idModel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `version` VARCHAR(45) NULL,
  `object` LONGBLOB NULL,
  PRIMARY KEY (`idModel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjectType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProjectType` (
  `idProjectType` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idProjectType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FeatureNameSpace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FeatureNameSpace` (
  `idFeatureNameSpace` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idFeatureNameSpace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Feature` (
  `idFeature` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `idFeatureNameSpace` INT NULL,
  PRIMARY KEY (`idFeature`),
  INDEX `fk_Feature_FeatureNameSpace1_idx` (`idFeatureNameSpace` ASC) VISIBLE,
  CONSTRAINT `fk_Feature_FeatureNameSpace1`
    FOREIGN KEY (`idFeatureNameSpace`)
    REFERENCES `mydb`.`FeatureNameSpace` (`idFeatureNameSpace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `idProjectType` INT NOT NULL,
  `idTargetFeature` INT NOT NULL,
  PRIMARY KEY (`idProject`, `idProjectType`),
  INDEX `fk_Project_ProjectType1_idx` (`idProjectType` ASC) VISIBLE,
  INDEX `fk_Project_Feature1_idx` (`idTargetFeature` ASC) VISIBLE,
  CONSTRAINT `fk_Project_ProjectType1`
    FOREIGN KEY (`idProjectType`)
    REFERENCES `mydb`.`ProjectType` (`idProjectType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Feature1`
    FOREIGN KEY (`idTargetFeature`)
    REFERENCES `mydb`.`Feature` (`idFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Run`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Run` (
  `idRun` INT NOT NULL AUTO_INCREMENT,
  `createdTimestamp` TIMESTAMP(6) NULL,
  `idTask` INT NULL,
  `idModel` INT NULL,
  `idProject` INT NULL,
  PRIMARY KEY (`idRun`),
  INDEX `fk_Run_Task1_idx` (`idTask` ASC) VISIBLE,
  INDEX `fk_Run_Flow1_idx` (`idModel` ASC) VISIBLE,
  INDEX `fk_Run_Project1_idx` (`idProject` ASC) VISIBLE,
  CONSTRAINT `fk_Run_Task1`
    FOREIGN KEY (`idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Run_Flow1`
    FOREIGN KEY (`idModel`)
    REFERENCES `mydb`.`Model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Run_Project1`
    FOREIGN KEY (`idProject`)
    REFERENCES `mydb`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EvaluationProcedure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EvaluationProcedure` (
  `idEvaluationProcedure` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idEvaluationProcedure`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Measure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Measure` (
  `idMeasure` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idMeasure`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MeasureValue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MeasureValue` (
  `idMeasureValue` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `idRun` INT NOT NULL,
  `idEvaluationProcedure` INT NOT NULL,
  `idMeasure` INT NOT NULL,
  PRIMARY KEY (`idMeasureValue`, `idEvaluationProcedure`),
  INDEX `fk_EvaluationMeasure_Run1_idx` (`idRun` ASC) VISIBLE,
  INDEX `fk_Measure_EvaluationProcedure1_idx` (`idEvaluationProcedure` ASC) VISIBLE,
  INDEX `fk_MeasureValue_Measure1_idx` (`idMeasure` ASC) VISIBLE,
  CONSTRAINT `fk_EvaluationMeasure_Run1`
    FOREIGN KEY (`idRun`)
    REFERENCES `mydb`.`Run` (`idRun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Measure_EvaluationProcedure1`
    FOREIGN KEY (`idEvaluationProcedure`)
    REFERENCES `mydb`.`EvaluationProcedure` (`idEvaluationProcedure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MeasureValue_Measure1`
    FOREIGN KEY (`idMeasure`)
    REFERENCES `mydb`.`Measure` (`idMeasure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ParameterType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ParameterType` (
  `idParameterType` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idParameterType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parameter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parameter` (
  `idParameter` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `idRun` INT NOT NULL,
  `idParameterType` INT NOT NULL,
  `valueType` VARCHAR(45) NULL,
  PRIMARY KEY (`idParameter`, `idParameterType`),
  INDEX `fk_ModelParameter_Run1_idx` (`idRun` ASC) VISIBLE,
  INDEX `fk_Parameter_ParameterType1_idx` (`idParameterType` ASC) VISIBLE,
  CONSTRAINT `fk_ModelParameter_Run1`
    FOREIGN KEY (`idRun`)
    REFERENCES `mydb`.`Run` (`idRun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parameter_ParameterType1`
    FOREIGN KEY (`idParameterType`)
    REFERENCES `mydb`.`ParameterType` (`idParameterType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FeatureImportance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FeatureImportance` (
  `idFeatureImportance` INT NOT NULL AUTO_INCREMENT,
  `importance` FLOAT NULL,
  `idRun` INT NOT NULL,
  `idFeature` INT NOT NULL,
  PRIMARY KEY (`idFeatureImportance`),
  INDEX `fk_FeatureImportance_Run1_idx` (`idRun` ASC) VISIBLE,
  INDEX `fk_FeatureImportance_Feature1_idx` (`idFeature` ASC) VISIBLE,
  CONSTRAINT `fk_FeatureImportance_Run1`
    FOREIGN KEY (`idRun`)
    REFERENCES `mydb`.`Run` (`idRun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FeatureImportance_Feature1`
    FOREIGN KEY (`idFeature`)
    REFERENCES `mydb`.`Feature` (`idFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prediction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prediction` (
  `idPrediction` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `idRun` INT NULL,
  `timestamp` TIMESTAMP(6) NULL,
  `idEntity` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrediction`),
  INDEX `fk_Prediction_Run1_idx` (`idRun` ASC) VISIBLE,
  CONSTRAINT `fk_Prediction_Run1`
    FOREIGN KEY (`idRun`)
    REFERENCES `mydb`.`Run` (`idRun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FeatureDataset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FeatureDataset` (
  `idFeatureDataset` INT NOT NULL AUTO_INCREMENT,
  `idDataset` INT NOT NULL,
  `idFeature` INT NOT NULL,
  PRIMARY KEY (`idFeatureDataset`),
  INDEX `fk_FeatureDataset_Dataset1_idx` (`idDataset` ASC) VISIBLE,
  INDEX `fk_FeatureDataset_Feature1_idx` (`idFeature` ASC) VISIBLE,
  CONSTRAINT `fk_FeatureDataset_Dataset1`
    FOREIGN KEY (`idDataset`)
    REFERENCES `mydb`.`Dataset` (`idDataset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FeatureDataset_Feature1`
    FOREIGN KEY (`idFeature`)
    REFERENCES `mydb`.`Feature` (`idFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PredictionFeatureContribution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PredictionFeatureContribution` (
  `idPredictionFeatureContribution` INT NOT NULL AUTO_INCREMENT,
  `contribution` DOUBLE NULL,
  `idFeature` INT NULL,
  `idPrediction` INT NOT NULL,
  PRIMARY KEY (`idPredictionFeatureContribution`),
  INDEX `fk_PredictionFeatureContribution_Feature1_idx` (`idFeature` ASC) VISIBLE,
  INDEX `fk_PredictionFeatureContribution_Prediction1_idx` (`idPrediction` ASC) VISIBLE,
  CONSTRAINT `fk_PredictionFeatureContribution_Feature1`
    FOREIGN KEY (`idFeature`)
    REFERENCES `mydb`.`Feature` (`idFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PredictionFeatureContribution_Prediction1`
    FOREIGN KEY (`idPrediction`)
    REFERENCES `mydb`.`Prediction` (`idPrediction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DriftTestMeasure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DriftTestMeasure` (
  `idDriftTestMeasure` INT NOT NULL AUTO_INCREMENT,
  `idMeasure` INT NOT NULL,
  `idReferenceMeasure` INT NOT NULL,
  PRIMARY KEY (`idDriftTestMeasure`),
  INDEX `fk_DriftTestMeasure_Measure1_idx` (`idMeasure` ASC) VISIBLE,
  INDEX `fk_DriftTestMeasure_Measure2_idx` (`idReferenceMeasure` ASC) VISIBLE,
  CONSTRAINT `fk_DriftTestMeasure_Measure1`
    FOREIGN KEY (`idMeasure`)
    REFERENCES `mydb`.`Measure` (`idMeasure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DriftTestMeasure_Measure2`
    FOREIGN KEY (`idReferenceMeasure`)
    REFERENCES `mydb`.`Measure` (`idMeasure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DriftTestFeature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DriftTestFeature` (
  `idDriftTestFeature` INT NOT NULL AUTO_INCREMENT,
  `idFeature` INT NOT NULL,
  `idMeasure` INT NOT NULL,
  PRIMARY KEY (`idDriftTestFeature`),
  INDEX `fk_DriftTestFeature_Feature1_idx` (`idFeature` ASC) VISIBLE,
  INDEX `fk_DriftTestFeature_Measure1_idx` (`idMeasure` ASC) VISIBLE,
  CONSTRAINT `fk_DriftTestFeature_Feature1`
    FOREIGN KEY (`idFeature`)
    REFERENCES `mydb`.`Feature` (`idFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DriftTestFeature_Measure1`
    FOREIGN KEY (`idMeasure`)
    REFERENCES `mydb`.`Measure` (`idMeasure`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`TaskType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`TaskType` (`idTaskType`, `type`) VALUES (1, 'Training');
INSERT INTO `mydb`.`TaskType` (`idTaskType`, `type`) VALUES (2, 'Prediction');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ProjectType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ProjectType` (`idProjectType`, `name`) VALUES (1, 'Classification');
INSERT INTO `mydb`.`ProjectType` (`idProjectType`, `name`) VALUES (2, 'Regression');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`ParameterType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`ParameterType` (`idParameterType`, `name`) VALUES (1, 'Model');
INSERT INTO `mydb`.`ParameterType` (`idParameterType`, `name`) VALUES (2, 'Task');

COMMIT;

